import type { BrandRecord } from "./types";

/** Abstract brand fleet — public-safe metadata only. No secrets. */
export const BRAND_REGISTRY: BrandRecord[] = [
  {
    name: "MindReply",
    slug: "mindreply",
    domain: "mind-reply.com",
    visibility: "public",
    source: "mindreply-org",
    vercelProject: "mindreply (production)",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "active",
    workflowStatus: "placeholder",
    supportPath: "/contact",
    nextAction: "Keep public site clean; no admin UI leak",
  },
  {
    name: "A11-K",
    slug: "a11-k",
    domain: "a11-k.space",
    visibility: "public",
    source: "a11-k-core",
    vercelProject: "a11-k-core",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "active",
    workflowStatus: "placeholder",
    supportPath: "/command → Support Queue",
    nextAction: "Connect engine cockpit + workflow routing (secure wiring when ready)",
  },
  {
    name: "AUREL",
    slug: "aurel",
    domain: "aurel.mind-reply.com",
    visibility: "public",
    source: "brands/aurel + frontend-aurel",
    vercelProject: "aurel",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "unknown",
    workflowStatus: "placeholder",
    supportPath: "command/support",
    nextAction: "Shape the secure connectivity framework; keep network claims strategy-only until verified",
  },
  {
    name: "Regex Forge",
    slug: "regex-forge",
    domain: "regex.mind-reply.com",
    visibility: "public",
    source: "regex-forge",
    vercelProject: "regex-forge",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "placeholder",
    supportPath: "tool intake → workflow automation regex_support",
    nextAction: "Wire intake workflow connection placeholder",
  },
  {
    name: "SQL Studio",
    slug: "sql-studio",
    domain: "sql.mind-reply.com",
    visibility: "public",
    source: "frontend-sql",
    vercelProject: "sql-studio",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "placeholder",
    supportPath: "tool intake → workflow automation sql_request",
    nextAction: "Wire SQL request workflow placeholder",
  },
  {
    name: "Code Tutor",
    slug: "code-tutor",
    domain: "tutor.mind-reply.com",
    visibility: "public",
    source: "frontend-tutor",
    vercelProject: "code-tutor",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "placeholder",
    supportPath: "tool intake → workflow automation tutor_request",
    nextAction: "Wire tutor request workflow",
  },
  {
    name: "Code Lens",
    slug: "code-lens",
    domain: "lens.mind-reply.com",
    visibility: "public",
    source: "frontend-lens",
    vercelProject: "code-lens",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "placeholder",
    supportPath: "tool intake → workflow automation code_lens_audit",
    nextAction: "Wire audit workflow placeholder",
  },
  {
    name: "SDR Agent",
    slug: "sdr-agent",
    domain: "sdr.mind-reply.com",
    visibility: "public",
    source: "frontend-sdr",
    vercelProject: "sdr-agent",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "placeholder",
    supportPath: "lead capture → workflow automation sdr_lead_sequence",
    nextAction: "Keep sequences placeholder until workflow wiring is confirmed",
  },
  {
    name: "L402 Skills",
    slug: "l402-skills",
    domain: "l402.mind-reply.com",
    visibility: "public",
    source: "frontend-l402",
    vercelProject: "l402-skills",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "placeholder",
    workflowStatus: "blocked",
    supportPath: "command/support",
    nextAction: "Document payment boundary before public promo",
  },
  {
    name: "AI Arena",
    slug: "ai-arena",
    domain: "ai-arena (vercel app)",
    visibility: "public",
    source: "brands/ai-arena",
    vercelProject: "ai-arena",
    githubRepo: "placeholder",
    status: "active",
    seoStatus: "unknown",
    workflowStatus: "placeholder",
    supportPath: "command/support",
    nextAction: "Confirm domain strategy vs a11-k models lane",
  },
  {
    name: "Aether-X",
    slug: "aether-x",
    domain: "aether-x / newai-arena",
    visibility: "stealth",
    source: "aether-x",
    vercelProject: "aether-x",
    githubRepo: "placeholder",
    status: "placeholder",
    seoStatus: "blocked",
    workflowStatus: "placeholder",
    supportPath: "command only",
    nextAction: "Keep stealth until product boundary defined",
  },
  {
    name: "Kratos-S",
    slug: "kratos-s",
    domain: "kratos-s.vercel.app",
    visibility: "stealth",
    source: "kratos-s",
    vercelProject: "kratos-s",
    githubRepo: "placeholder",
    status: "placeholder",
    seoStatus: "blocked",
    workflowStatus: "placeholder",
    supportPath: "command only",
    nextAction: "Stealth lab module only",
  },
  {
    name: "BRIXO",
    slug: "brixo",
    domain: "unknown",
    visibility: "stealth",
    source: "not found in estate",
    vercelProject: "none",
    githubRepo: "none",
    status: "blocked",
    seoStatus: "blocked",
    workflowStatus: "blocked",
    supportPath: "ideas vault",
    nextAction: "No source found — keep abstract stub only",
  },
  {
    name: "Meridian",
    slug: "meridian",
    domain: "not public",
    visibility: "stealth",
    source: "luxury hospitality brand guidelines (OneDrive clues)",
    vercelProject: "none",
    githubRepo: "none",
    status: "placeholder",
    seoStatus: "blocked",
    workflowStatus: "placeholder",
    supportPath: "command/ideas",
    nextAction: "Develop as luxury hospitality idea pack only",
  },
  {
    name: "Yacht / Marina Luxury",
    slug: "yacht-luxury",
    domain: "not public",
    visibility: "stealth",
    source: "No explicit yacht source found",
    vercelProject: "none",
    githubRepo: "none",
    status: "blocked",
    seoStatus: "blocked",
    workflowStatus: "blocked",
    supportPath: "command/ideas",
    nextAction:
      "No explicit yacht source found. Closest confirmed source is Meridian luxury hospitality.",
  },
];

