import type { WorkflowRecord } from "./types";
import { missingEnv } from "./env";

export const WORKFLOWS: WorkflowRecord[] = [
  {
    id: "brand_status_check",
    name: "Brand Status Check",
    purpose: "Poll brand URLs and score estate health",
    trigger: "schedule",
    inputFields: ["brand_id", "site_url"],
    connectionPath: "/workflow connection/brand-status-check",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY"],
    dashboardAction: "View last status (when wired)",
    status: "placeholder",
  },
  {
    id: "site_down_alert",
    name: "Site Down Alert",
    purpose: "Escalate production downtime",
    trigger: "schedule / workflow connection",
    inputFields: ["url", "http_status"],
    connectionPath: "/workflow connection/site-down-alert",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY", "SUPPORT_EMAIL_TO"],
    dashboardAction: "Open escalations",
    status: "blocked",
  },
  {
    id: "public_intake",
    name: "Public Intake",
    purpose: "Website form → support record",
    trigger: "website_form_submit",
    inputFields: ["name", "email", "site", "issue_type", "urgency", "message", "consent"],
    connectionPath: "/workflow connection/public-intake",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET", "SUPPORT_EMAIL_TO"],
    dashboardAction: "Open support queue",
    status: "blocked",
  },
  {
    id: "chat_escalation",
    name: "Chat Escalation",
    purpose: "Route high-risk chat to Angel format",
    trigger: "chat_risk_signal",
    inputFields: ["severity", "summary", "brand"],
    connectionPath: "/workflow connection/chat-escalation",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY"],
    dashboardAction: "Review escalation draft",
    status: "placeholder",
  },
  {
    id: "lead_capture",
    name: "Lead Capture",
    purpose: "Capture leads from public CTAs",
    trigger: "form_submit",
    inputFields: ["name", "email", "source"],
    connectionPath: "/workflow connection/lead-capture",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    dashboardAction: "View lead list",
    status: "placeholder",
  },
  {
    id: "customer_support_routing",
    name: "Customer Support Routing",
    purpose: "Classify and route support tickets",
    trigger: "support_record_created",
    inputFields: ["ticket_id", "urgency", "topic"],
    connectionPath: "/workflow connection/support-routing",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY"],
    dashboardAction: "Open support queue",
    status: "placeholder",
  },
  {
    id: "seo_monitor",
    name: "SEO Monitor",
    purpose: "Track priority page metadata health",
    trigger: "schedule",
    inputFields: ["path", "canonical"],
    connectionPath: "/workflow connection/seo-monitor",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "SEO panel",
    status: "placeholder",
  },
  {
    id: "deployment_watch",
    name: "Deployment Watch",
    purpose: "Watch GitHub/Vercel deploy state",
    trigger: "schedule / vercel workflow connection",
    inputFields: ["project", "commit", "status"],
    connectionPath: "/workflow connection/deployment-watch",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "VERCEL_TOKEN", "GITHUB_TOKEN"],
    dashboardAction: "Deployments table",
    status: "blocked",
  },
  {
    id: "weekly_operating_report",
    name: "Weekly Operating Report",
    purpose: "Owner weekly digest",
    trigger: "cron weekly",
    inputFields: ["week_of"],
    connectionPath: "/workflow connection/weekly-report",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "SUPPORT_EMAIL_TO"],
    dashboardAction: "Reports",
    status: "placeholder",
  },
  {
    id: "idea_intake",
    name: "Idea Intake",
    purpose: "Capture ideas into vault",
    trigger: "manual / form",
    inputFields: ["title", "source", "summary"],
    connectionPath: "/workflow connection/idea-intake",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Ideas vault",
    status: "placeholder",
  },
  {
    id: "luxury_meridian_review",
    name: "Luxury / Meridian / Yacht Review",
    purpose: "Review hospitality idea pack (stealth)",
    trigger: "manual",
    inputFields: ["idea_id", "notes"],
    connectionPath: "/workflow connection/luxury-review",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Shadow / Ideas",
    status: "placeholder",
  },
  {
    id: "shadow_estate_sync",
    name: "Shadow Estate Sync",
    purpose: "Sync shadow twins without public data leak",
    trigger: "schedule",
    inputFields: ["twin_id"],
    connectionPath: "/workflow connection/shadow-sync",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Operating Twin",
    status: "placeholder",
  },
  {
    id: "decision_preflight",
    name: "Decision Preflight",
    purpose: "Risk check before controlled production",
    trigger: "before_deploy",
    inputFields: ["action", "risk"],
    connectionPath: "/workflow connection/decision-preflight",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Simulation",
    status: "placeholder",
  },
  {
    id: "action_queue_update",
    name: "Action Queue Update",
    purpose: "Push/pull action queue items",
    trigger: "event",
    inputFields: ["action_id", "status"],
    connectionPath: "/workflow connection/action-queue",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Action queue",
    status: "placeholder",
  },
  {
    id: "model_availability_check",
    name: "Model Availability Check",
    purpose: "Check provider env presence (no secret values)",
    trigger: "schedule",
    inputFields: ["provider"],
    connectionPath: "/workflow connection/model-availability",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL"],
    dashboardAction: "Models",
    status: "placeholder",
  },
  {
    id: "sql_request",
    name: "SQL request",
    purpose: "Tool-specific SQL Studio intake",
    trigger: "tool_form",
    inputFields: ["query_need", "email"],
    connectionPath: "/workflow connection/sql-request",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    dashboardAction: "Tool workflows",
    status: "placeholder",
  },
  {
    id: "code_lens_audit",
    name: "Code Lens audit",
    purpose: "Code Lens audit request",
    trigger: "tool_form",
    inputFields: ["repo_or_snippet", "email"],
    connectionPath: "/workflow connection/code-lens-audit",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    dashboardAction: "Tool workflows",
    status: "placeholder",
  },
  {
    id: "sdr_lead_sequence",
    name: "SDR lead sequence",
    purpose: "SDR sequence (stealth until credentials)",
    trigger: "lead_created",
    inputFields: ["lead_id"],
    connectionPath: "/workflow connection/sdr-lead-sequence",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY"],
    dashboardAction: "SDR panel",
    status: "blocked",
  },
  {
    id: "regex_support",
    name: "Regex support",
    purpose: "Regex Forge support path",
    trigger: "tool_form",
    inputFields: ["pattern_need", "email"],
    connectionPath: "/workflow connection/regex-support",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    dashboardAction: "Tool workflows",
    status: "placeholder",
  },
  {
    id: "tutor_request",
    name: "Tutor request",
    purpose: "Code Tutor request path",
    trigger: "tool_form",
    inputFields: ["topic", "email"],
    connectionPath: "/workflow connection/tutor-request",
    webhookStatus: "placeholder",
    requiredEnv: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    dashboardAction: "Tool workflows",
    status: "placeholder",
  },
];

export function n8nBlockedBy(): string[] {
  return missingEnv(["N8N_BASE_URL", "N8N_API_KEY"]);
}
